apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-grpc
  name: udaconnect-location-grpc
spec:
  ports:
  - name: "5000"
    port: 5005
    targetPort: 5005
    nodePort: 30001
  selector:
    service: udaconnect-location-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-grpc
  name: udaconnect-location-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-grpc
  template:
    metadata:
      labels:
        service: udaconnect-location-grpc
    spec:
      containers:
      - image: gilang1997/udaconnect-location-grpc:v1.0.0
        name: udaconnect-location-grpc
        imagePullPolicy: Always
        env:
        - name: KAFKA_TOPIC
          value: "test"
        - name: KAFKA_HOST
          value: "my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local"
        - name: KAFKA_PORT
          value: "9092"
        - name: DB_USERNAME
          value: "ct_admin"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "geoconnections"
      restartPolicy: Always
